FROM python:3.13-alpine
WORKDIR /app

RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt /app/

RUN python -m venv venv
RUN source venv/bin/activate
RUN pip install -r requirements.txt

RUN apk add --no-cache make

COPY . /app

CMD ["make", "test.coverage.report"]
